### ISSUE TITLE
Issue when Arduino-mk has been installed from the official repo.

### ISSUE THREAD

**Issue by fjrg76mx** [ladislas/Bare-Arduino-Project#47]
First of all, congrats for this project, it's what I was looking for for a long time! But while using it for the first time I had to tweak it so that it works in my Linux box (Linux Mint 18.2, Cinnamon). **If you've installed Arduino-mk from the repos** as I did, then your makefile template must be updated as shown below once it was copied to the project folder. 

I had to swap the order of these instructions so the last one works as expected:

```
### Path to the Arduino application and ressources directory.
ARDUINO_DIR       = /usr/share/arduino

### ARDMK_DIR
### Path to the Arduino-Makefile directory.
ARDMK_DIR         = $(ARDUINO_DIR)

```
By the way, in the last line it's read:

`### path to Arduino.mk, inside the ARDMK_DIR, don't touch.
`
however, such a directory is empty. Perhaps it's my fault 'cause I forget something to copy into it.

May be it's not the right place, nor it's related to the original issue, but in Linux (as far as I know, and I'm not an expert) there is not such a thing:

`MONITOR_PORT      = /dev/tty.usbmodem*
`
instead one uses:

`MONITOR_PORT      = /dev/ttyUSB*`

or

`MONITOR_PORT      = /dev/ttyACM*`

Thanks for your project and I'll keep using it. Any other issue you'll be notified.

**Comment by ladislas** [comment]
thanks @fjrg76mx for the feedback.

I'll change the monitor port that was set for OS X and not Linux, you're right.

For the rest, this is specific to your case. If you `git clone --recursive` the repo, you'll have Arduino-MK as a submodule and won't need to update anything. it is important as the project uses some magic to recursively find the included libraries so you don't have to reference them all.

otherwise you can do you trick but you might run into issues.
